project:
  type: website

website:
  title: "Paul's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sapolraadnui

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
